### ISSUE TITLE
Missing closing <p> tag

### ISSUE THREAD

**Issue by TheIrishBub** [ScottJohnson02/ScottJohnson.github.io#1]
Not too big of an issue, as the site works just fine without it, but it was something I noticed in the HTML code.

It was on index.html, line 41.

https://github.com/ScottJohnson02/ScottJohnson02.github.io/blob/0fe88a584bb72d7893c6ae9e95de7fedcbddf837/index.html#L41

**Comment by zachfedor** [comment]
@TheIrishBub please add the link to the line and file.
